# Autogenerated wrapper script for STL_jll for aarch64-apple-darwin
export libSTL

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("STL")
JLLWrappers.@declare_library_product(libSTL, "@rpath/libSTL.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libSTL,
        "lib/libSTL.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
