# Autogenerated wrapper script for STL_jll for x86_64-w64-mingw32-cxx03
export libSTL

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("STL")
JLLWrappers.@declare_library_product(libSTL, "libSTL.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libSTL,
        "bin\\libSTL.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
